function Menu() {
    let thefun = document.getElementById('3NPF');
    thefun.style.backgroundColor='red';
    thefun.style.color='yellow';
}

function Services() {
    let thefun = document.getElementById('2NPF');
    let p = document.createElement('p');
    p.innerText = 'WELCOME';
    thefun.appendChild(p);
}

function Help() {
var element = document.getElementById('4NPF');
element.classList.add('maday');
}